// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: internal/diffusion_service.proto

#include "internal/diffusion_service.pb.h"
#include "internal/diffusion_service.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace infaas {
namespace internal {

static const char* DiffusionService_method_names[] = {
  "/infaas.internal.DiffusionService/Generate",
};

std::unique_ptr< DiffusionService::Stub> DiffusionService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DiffusionService::Stub> stub(new DiffusionService::Stub(channel, options));
  return stub;
}

DiffusionService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Generate_(DiffusionService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status DiffusionService::Stub::Generate(::grpc::ClientContext* context, const ::infaas::internal::DiffusionRequest& request, ::infaas::internal::DiffusionReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::infaas::internal::DiffusionRequest, ::infaas::internal::DiffusionReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Generate_, context, request, response);
}

void DiffusionService::Stub::async::Generate(::grpc::ClientContext* context, const ::infaas::internal::DiffusionRequest* request, ::infaas::internal::DiffusionReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::infaas::internal::DiffusionRequest, ::infaas::internal::DiffusionReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Generate_, context, request, response, std::move(f));
}

void DiffusionService::Stub::async::Generate(::grpc::ClientContext* context, const ::infaas::internal::DiffusionRequest* request, ::infaas::internal::DiffusionReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Generate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::infaas::internal::DiffusionReply>* DiffusionService::Stub::PrepareAsyncGenerateRaw(::grpc::ClientContext* context, const ::infaas::internal::DiffusionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::infaas::internal::DiffusionReply, ::infaas::internal::DiffusionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Generate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::infaas::internal::DiffusionReply>* DiffusionService::Stub::AsyncGenerateRaw(::grpc::ClientContext* context, const ::infaas::internal::DiffusionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGenerateRaw(context, request, cq);
  result->StartCall();
  return result;
}

DiffusionService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DiffusionService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DiffusionService::Service, ::infaas::internal::DiffusionRequest, ::infaas::internal::DiffusionReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DiffusionService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::infaas::internal::DiffusionRequest* req,
             ::infaas::internal::DiffusionReply* resp) {
               return service->Generate(ctx, req, resp);
             }, this)));
}

DiffusionService::Service::~Service() {
}

::grpc::Status DiffusionService::Service::Generate(::grpc::ServerContext* context, const ::infaas::internal::DiffusionRequest* request, ::infaas::internal::DiffusionReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace infaas
}  // namespace internal

