// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal/diffusion_service.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_internal_2fdiffusion_5fservice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_internal_2fdiffusion_5fservice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_internal_2fdiffusion_5fservice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_internal_2fdiffusion_5fservice_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_internal_2fdiffusion_5fservice_2eproto;
namespace infaas {
namespace internal {
class DiffusionReply;
struct DiffusionReplyDefaultTypeInternal;
extern DiffusionReplyDefaultTypeInternal _DiffusionReply_default_instance_;
class DiffusionRequest;
struct DiffusionRequestDefaultTypeInternal;
extern DiffusionRequestDefaultTypeInternal _DiffusionRequest_default_instance_;
}  // namespace internal
}  // namespace infaas
PROTOBUF_NAMESPACE_OPEN
template<> ::infaas::internal::DiffusionReply* Arena::CreateMaybeMessage<::infaas::internal::DiffusionReply>(Arena*);
template<> ::infaas::internal::DiffusionRequest* Arena::CreateMaybeMessage<::infaas::internal::DiffusionRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace infaas {
namespace internal {

// ===================================================================

class DiffusionRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:infaas.internal.DiffusionRequest) */ {
 public:
  inline DiffusionRequest() : DiffusionRequest(nullptr) {}
  ~DiffusionRequest() override;
  explicit constexpr DiffusionRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DiffusionRequest(const DiffusionRequest& from);
  DiffusionRequest(DiffusionRequest&& from) noexcept
    : DiffusionRequest() {
    *this = ::std::move(from);
  }

  inline DiffusionRequest& operator=(const DiffusionRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline DiffusionRequest& operator=(DiffusionRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DiffusionRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const DiffusionRequest* internal_default_instance() {
    return reinterpret_cast<const DiffusionRequest*>(
               &_DiffusionRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DiffusionRequest& a, DiffusionRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(DiffusionRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DiffusionRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DiffusionRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DiffusionRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DiffusionRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const DiffusionRequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DiffusionRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "infaas.internal.DiffusionRequest";
  }
  protected:
  explicit DiffusionRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPromptFieldNumber = 1,
    kModelFieldNumber = 2,
    kInputTextFieldNumber = 8,
    kStepsFieldNumber = 3,
    kGuidanceScaleFieldNumber = 4,
    kSeedFieldNumber = 5,
    kWidthFieldNumber = 6,
    kHeightFieldNumber = 7,
  };
  // string prompt = 1;
  void clear_prompt();
  const std::string& prompt() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_prompt(ArgT0&& arg0, ArgT... args);
  std::string* mutable_prompt();
  PROTOBUF_NODISCARD std::string* release_prompt();
  void set_allocated_prompt(std::string* prompt);
  private:
  const std::string& _internal_prompt() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_prompt(const std::string& value);
  std::string* _internal_mutable_prompt();
  public:

  // string model = 2;
  void clear_model();
  const std::string& model() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_model(ArgT0&& arg0, ArgT... args);
  std::string* mutable_model();
  PROTOBUF_NODISCARD std::string* release_model();
  void set_allocated_model(std::string* model);
  private:
  const std::string& _internal_model() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_model(const std::string& value);
  std::string* _internal_mutable_model();
  public:

  // string input_text = 8;
  void clear_input_text();
  const std::string& input_text() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_input_text(ArgT0&& arg0, ArgT... args);
  std::string* mutable_input_text();
  PROTOBUF_NODISCARD std::string* release_input_text();
  void set_allocated_input_text(std::string* input_text);
  private:
  const std::string& _internal_input_text() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_input_text(const std::string& value);
  std::string* _internal_mutable_input_text();
  public:

  // int32 steps = 3;
  void clear_steps();
  int32_t steps() const;
  void set_steps(int32_t value);
  private:
  int32_t _internal_steps() const;
  void _internal_set_steps(int32_t value);
  public:

  // float guidanceScale = 4;
  void clear_guidancescale();
  float guidancescale() const;
  void set_guidancescale(float value);
  private:
  float _internal_guidancescale() const;
  void _internal_set_guidancescale(float value);
  public:

  // int32 seed = 5;
  void clear_seed();
  int32_t seed() const;
  void set_seed(int32_t value);
  private:
  int32_t _internal_seed() const;
  void _internal_set_seed(int32_t value);
  public:

  // int32 width = 6;
  void clear_width();
  int32_t width() const;
  void set_width(int32_t value);
  private:
  int32_t _internal_width() const;
  void _internal_set_width(int32_t value);
  public:

  // int32 height = 7;
  void clear_height();
  int32_t height() const;
  void set_height(int32_t value);
  private:
  int32_t _internal_height() const;
  void _internal_set_height(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:infaas.internal.DiffusionRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr prompt_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr model_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr input_text_;
  int32_t steps_;
  float guidancescale_;
  int32_t seed_;
  int32_t width_;
  int32_t height_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_internal_2fdiffusion_5fservice_2eproto;
};
// -------------------------------------------------------------------

class DiffusionReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:infaas.internal.DiffusionReply) */ {
 public:
  inline DiffusionReply() : DiffusionReply(nullptr) {}
  ~DiffusionReply() override;
  explicit constexpr DiffusionReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DiffusionReply(const DiffusionReply& from);
  DiffusionReply(DiffusionReply&& from) noexcept
    : DiffusionReply() {
    *this = ::std::move(from);
  }

  inline DiffusionReply& operator=(const DiffusionReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline DiffusionReply& operator=(DiffusionReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DiffusionReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const DiffusionReply* internal_default_instance() {
    return reinterpret_cast<const DiffusionReply*>(
               &_DiffusionReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(DiffusionReply& a, DiffusionReply& b) {
    a.Swap(&b);
  }
  inline void Swap(DiffusionReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DiffusionReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DiffusionReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DiffusionReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DiffusionReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const DiffusionReply& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DiffusionReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "infaas.internal.DiffusionReply";
  }
  protected:
  explicit DiffusionReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kImagePngFieldNumber = 1,
    kImagePathFieldNumber = 2,
    kStatusFieldNumber = 3,
    kErrorMsgFieldNumber = 4,
  };
  // bytes image_png = 1;
  void clear_image_png();
  const std::string& image_png() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_image_png(ArgT0&& arg0, ArgT... args);
  std::string* mutable_image_png();
  PROTOBUF_NODISCARD std::string* release_image_png();
  void set_allocated_image_png(std::string* image_png);
  private:
  const std::string& _internal_image_png() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_image_png(const std::string& value);
  std::string* _internal_mutable_image_png();
  public:

  // string image_path = 2;
  void clear_image_path();
  const std::string& image_path() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_image_path(ArgT0&& arg0, ArgT... args);
  std::string* mutable_image_path();
  PROTOBUF_NODISCARD std::string* release_image_path();
  void set_allocated_image_path(std::string* image_path);
  private:
  const std::string& _internal_image_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_image_path(const std::string& value);
  std::string* _internal_mutable_image_path();
  public:

  // string status = 3;
  void clear_status();
  const std::string& status() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_status(ArgT0&& arg0, ArgT... args);
  std::string* mutable_status();
  PROTOBUF_NODISCARD std::string* release_status();
  void set_allocated_status(std::string* status);
  private:
  const std::string& _internal_status() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_status(const std::string& value);
  std::string* _internal_mutable_status();
  public:

  // string error_msg = 4;
  void clear_error_msg();
  const std::string& error_msg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error_msg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error_msg();
  PROTOBUF_NODISCARD std::string* release_error_msg();
  void set_allocated_error_msg(std::string* error_msg);
  private:
  const std::string& _internal_error_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error_msg(const std::string& value);
  std::string* _internal_mutable_error_msg();
  public:

  // @@protoc_insertion_point(class_scope:infaas.internal.DiffusionReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr image_png_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr image_path_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr status_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_msg_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_internal_2fdiffusion_5fservice_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DiffusionRequest

// string prompt = 1;
inline void DiffusionRequest::clear_prompt() {
  prompt_.ClearToEmpty();
}
inline const std::string& DiffusionRequest::prompt() const {
  // @@protoc_insertion_point(field_get:infaas.internal.DiffusionRequest.prompt)
  return _internal_prompt();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DiffusionRequest::set_prompt(ArgT0&& arg0, ArgT... args) {
 
 prompt_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:infaas.internal.DiffusionRequest.prompt)
}
inline std::string* DiffusionRequest::mutable_prompt() {
  std::string* _s = _internal_mutable_prompt();
  // @@protoc_insertion_point(field_mutable:infaas.internal.DiffusionRequest.prompt)
  return _s;
}
inline const std::string& DiffusionRequest::_internal_prompt() const {
  return prompt_.Get();
}
inline void DiffusionRequest::_internal_set_prompt(const std::string& value) {
  
  prompt_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* DiffusionRequest::_internal_mutable_prompt() {
  
  return prompt_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* DiffusionRequest::release_prompt() {
  // @@protoc_insertion_point(field_release:infaas.internal.DiffusionRequest.prompt)
  return prompt_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void DiffusionRequest::set_allocated_prompt(std::string* prompt) {
  if (prompt != nullptr) {
    
  } else {
    
  }
  prompt_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), prompt,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (prompt_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    prompt_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:infaas.internal.DiffusionRequest.prompt)
}

// string model = 2;
inline void DiffusionRequest::clear_model() {
  model_.ClearToEmpty();
}
inline const std::string& DiffusionRequest::model() const {
  // @@protoc_insertion_point(field_get:infaas.internal.DiffusionRequest.model)
  return _internal_model();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DiffusionRequest::set_model(ArgT0&& arg0, ArgT... args) {
 
 model_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:infaas.internal.DiffusionRequest.model)
}
inline std::string* DiffusionRequest::mutable_model() {
  std::string* _s = _internal_mutable_model();
  // @@protoc_insertion_point(field_mutable:infaas.internal.DiffusionRequest.model)
  return _s;
}
inline const std::string& DiffusionRequest::_internal_model() const {
  return model_.Get();
}
inline void DiffusionRequest::_internal_set_model(const std::string& value) {
  
  model_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* DiffusionRequest::_internal_mutable_model() {
  
  return model_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* DiffusionRequest::release_model() {
  // @@protoc_insertion_point(field_release:infaas.internal.DiffusionRequest.model)
  return model_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void DiffusionRequest::set_allocated_model(std::string* model) {
  if (model != nullptr) {
    
  } else {
    
  }
  model_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), model,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (model_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    model_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:infaas.internal.DiffusionRequest.model)
}

// int32 steps = 3;
inline void DiffusionRequest::clear_steps() {
  steps_ = 0;
}
inline int32_t DiffusionRequest::_internal_steps() const {
  return steps_;
}
inline int32_t DiffusionRequest::steps() const {
  // @@protoc_insertion_point(field_get:infaas.internal.DiffusionRequest.steps)
  return _internal_steps();
}
inline void DiffusionRequest::_internal_set_steps(int32_t value) {
  
  steps_ = value;
}
inline void DiffusionRequest::set_steps(int32_t value) {
  _internal_set_steps(value);
  // @@protoc_insertion_point(field_set:infaas.internal.DiffusionRequest.steps)
}

// float guidanceScale = 4;
inline void DiffusionRequest::clear_guidancescale() {
  guidancescale_ = 0;
}
inline float DiffusionRequest::_internal_guidancescale() const {
  return guidancescale_;
}
inline float DiffusionRequest::guidancescale() const {
  // @@protoc_insertion_point(field_get:infaas.internal.DiffusionRequest.guidanceScale)
  return _internal_guidancescale();
}
inline void DiffusionRequest::_internal_set_guidancescale(float value) {
  
  guidancescale_ = value;
}
inline void DiffusionRequest::set_guidancescale(float value) {
  _internal_set_guidancescale(value);
  // @@protoc_insertion_point(field_set:infaas.internal.DiffusionRequest.guidanceScale)
}

// int32 seed = 5;
inline void DiffusionRequest::clear_seed() {
  seed_ = 0;
}
inline int32_t DiffusionRequest::_internal_seed() const {
  return seed_;
}
inline int32_t DiffusionRequest::seed() const {
  // @@protoc_insertion_point(field_get:infaas.internal.DiffusionRequest.seed)
  return _internal_seed();
}
inline void DiffusionRequest::_internal_set_seed(int32_t value) {
  
  seed_ = value;
}
inline void DiffusionRequest::set_seed(int32_t value) {
  _internal_set_seed(value);
  // @@protoc_insertion_point(field_set:infaas.internal.DiffusionRequest.seed)
}

// int32 width = 6;
inline void DiffusionRequest::clear_width() {
  width_ = 0;
}
inline int32_t DiffusionRequest::_internal_width() const {
  return width_;
}
inline int32_t DiffusionRequest::width() const {
  // @@protoc_insertion_point(field_get:infaas.internal.DiffusionRequest.width)
  return _internal_width();
}
inline void DiffusionRequest::_internal_set_width(int32_t value) {
  
  width_ = value;
}
inline void DiffusionRequest::set_width(int32_t value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:infaas.internal.DiffusionRequest.width)
}

// int32 height = 7;
inline void DiffusionRequest::clear_height() {
  height_ = 0;
}
inline int32_t DiffusionRequest::_internal_height() const {
  return height_;
}
inline int32_t DiffusionRequest::height() const {
  // @@protoc_insertion_point(field_get:infaas.internal.DiffusionRequest.height)
  return _internal_height();
}
inline void DiffusionRequest::_internal_set_height(int32_t value) {
  
  height_ = value;
}
inline void DiffusionRequest::set_height(int32_t value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:infaas.internal.DiffusionRequest.height)
}

// string input_text = 8;
inline void DiffusionRequest::clear_input_text() {
  input_text_.ClearToEmpty();
}
inline const std::string& DiffusionRequest::input_text() const {
  // @@protoc_insertion_point(field_get:infaas.internal.DiffusionRequest.input_text)
  return _internal_input_text();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DiffusionRequest::set_input_text(ArgT0&& arg0, ArgT... args) {
 
 input_text_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:infaas.internal.DiffusionRequest.input_text)
}
inline std::string* DiffusionRequest::mutable_input_text() {
  std::string* _s = _internal_mutable_input_text();
  // @@protoc_insertion_point(field_mutable:infaas.internal.DiffusionRequest.input_text)
  return _s;
}
inline const std::string& DiffusionRequest::_internal_input_text() const {
  return input_text_.Get();
}
inline void DiffusionRequest::_internal_set_input_text(const std::string& value) {
  
  input_text_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* DiffusionRequest::_internal_mutable_input_text() {
  
  return input_text_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* DiffusionRequest::release_input_text() {
  // @@protoc_insertion_point(field_release:infaas.internal.DiffusionRequest.input_text)
  return input_text_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void DiffusionRequest::set_allocated_input_text(std::string* input_text) {
  if (input_text != nullptr) {
    
  } else {
    
  }
  input_text_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), input_text,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (input_text_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    input_text_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:infaas.internal.DiffusionRequest.input_text)
}

// -------------------------------------------------------------------

// DiffusionReply

// bytes image_png = 1;
inline void DiffusionReply::clear_image_png() {
  image_png_.ClearToEmpty();
}
inline const std::string& DiffusionReply::image_png() const {
  // @@protoc_insertion_point(field_get:infaas.internal.DiffusionReply.image_png)
  return _internal_image_png();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DiffusionReply::set_image_png(ArgT0&& arg0, ArgT... args) {
 
 image_png_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:infaas.internal.DiffusionReply.image_png)
}
inline std::string* DiffusionReply::mutable_image_png() {
  std::string* _s = _internal_mutable_image_png();
  // @@protoc_insertion_point(field_mutable:infaas.internal.DiffusionReply.image_png)
  return _s;
}
inline const std::string& DiffusionReply::_internal_image_png() const {
  return image_png_.Get();
}
inline void DiffusionReply::_internal_set_image_png(const std::string& value) {
  
  image_png_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* DiffusionReply::_internal_mutable_image_png() {
  
  return image_png_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* DiffusionReply::release_image_png() {
  // @@protoc_insertion_point(field_release:infaas.internal.DiffusionReply.image_png)
  return image_png_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void DiffusionReply::set_allocated_image_png(std::string* image_png) {
  if (image_png != nullptr) {
    
  } else {
    
  }
  image_png_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), image_png,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (image_png_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    image_png_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:infaas.internal.DiffusionReply.image_png)
}

// string image_path = 2;
inline void DiffusionReply::clear_image_path() {
  image_path_.ClearToEmpty();
}
inline const std::string& DiffusionReply::image_path() const {
  // @@protoc_insertion_point(field_get:infaas.internal.DiffusionReply.image_path)
  return _internal_image_path();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DiffusionReply::set_image_path(ArgT0&& arg0, ArgT... args) {
 
 image_path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:infaas.internal.DiffusionReply.image_path)
}
inline std::string* DiffusionReply::mutable_image_path() {
  std::string* _s = _internal_mutable_image_path();
  // @@protoc_insertion_point(field_mutable:infaas.internal.DiffusionReply.image_path)
  return _s;
}
inline const std::string& DiffusionReply::_internal_image_path() const {
  return image_path_.Get();
}
inline void DiffusionReply::_internal_set_image_path(const std::string& value) {
  
  image_path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* DiffusionReply::_internal_mutable_image_path() {
  
  return image_path_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* DiffusionReply::release_image_path() {
  // @@protoc_insertion_point(field_release:infaas.internal.DiffusionReply.image_path)
  return image_path_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void DiffusionReply::set_allocated_image_path(std::string* image_path) {
  if (image_path != nullptr) {
    
  } else {
    
  }
  image_path_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), image_path,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (image_path_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    image_path_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:infaas.internal.DiffusionReply.image_path)
}

// string status = 3;
inline void DiffusionReply::clear_status() {
  status_.ClearToEmpty();
}
inline const std::string& DiffusionReply::status() const {
  // @@protoc_insertion_point(field_get:infaas.internal.DiffusionReply.status)
  return _internal_status();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DiffusionReply::set_status(ArgT0&& arg0, ArgT... args) {
 
 status_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:infaas.internal.DiffusionReply.status)
}
inline std::string* DiffusionReply::mutable_status() {
  std::string* _s = _internal_mutable_status();
  // @@protoc_insertion_point(field_mutable:infaas.internal.DiffusionReply.status)
  return _s;
}
inline const std::string& DiffusionReply::_internal_status() const {
  return status_.Get();
}
inline void DiffusionReply::_internal_set_status(const std::string& value) {
  
  status_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* DiffusionReply::_internal_mutable_status() {
  
  return status_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* DiffusionReply::release_status() {
  // @@protoc_insertion_point(field_release:infaas.internal.DiffusionReply.status)
  return status_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void DiffusionReply::set_allocated_status(std::string* status) {
  if (status != nullptr) {
    
  } else {
    
  }
  status_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), status,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (status_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    status_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:infaas.internal.DiffusionReply.status)
}

// string error_msg = 4;
inline void DiffusionReply::clear_error_msg() {
  error_msg_.ClearToEmpty();
}
inline const std::string& DiffusionReply::error_msg() const {
  // @@protoc_insertion_point(field_get:infaas.internal.DiffusionReply.error_msg)
  return _internal_error_msg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DiffusionReply::set_error_msg(ArgT0&& arg0, ArgT... args) {
 
 error_msg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:infaas.internal.DiffusionReply.error_msg)
}
inline std::string* DiffusionReply::mutable_error_msg() {
  std::string* _s = _internal_mutable_error_msg();
  // @@protoc_insertion_point(field_mutable:infaas.internal.DiffusionReply.error_msg)
  return _s;
}
inline const std::string& DiffusionReply::_internal_error_msg() const {
  return error_msg_.Get();
}
inline void DiffusionReply::_internal_set_error_msg(const std::string& value) {
  
  error_msg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* DiffusionReply::_internal_mutable_error_msg() {
  
  return error_msg_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* DiffusionReply::release_error_msg() {
  // @@protoc_insertion_point(field_release:infaas.internal.DiffusionReply.error_msg)
  return error_msg_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void DiffusionReply::set_allocated_error_msg(std::string* error_msg) {
  if (error_msg != nullptr) {
    
  } else {
    
  }
  error_msg_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), error_msg,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (error_msg_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    error_msg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:infaas.internal.DiffusionReply.error_msg)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace internal
}  // namespace infaas

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_internal_2fdiffusion_5fservice_2eproto
