# Author: KB 
# Date: 2026-03-06 
# Purpose: For keeping configuration settings 
# File: config.py 

SCALE_UP_THRESHOLD = 5
SCALE_DOWN_THRESHOLD = 1

UTILIZATION_SCALE_UP = 0.8
UTILIZATION_SCALE_DOWN = 0.3

MIN_WORKERS = 1
MAX_WORKERS = 5

AUTOSCALE_INTERVAL = 5
CHECK_INTERVAL = 5
