// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: infaas_request_status.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_infaas_5frequest_5fstatus_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_infaas_5frequest_5fstatus_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_infaas_5frequest_5fstatus_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_infaas_5frequest_5fstatus_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_infaas_5frequest_5fstatus_2eproto;
namespace infaas {
namespace internal {
class InfaasRequestStatus;
struct InfaasRequestStatusDefaultTypeInternal;
extern InfaasRequestStatusDefaultTypeInternal _InfaasRequestStatus_default_instance_;
}  // namespace internal
}  // namespace infaas
PROTOBUF_NAMESPACE_OPEN
template<> ::infaas::internal::InfaasRequestStatus* Arena::CreateMaybeMessage<::infaas::internal::InfaasRequestStatus>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace infaas {
namespace internal {

enum InfaasRequestStatusEnum : int {
  INVALID = 0,
  SUCCESS = 1,
  UNAVAILABLE = 2,
  InfaasRequestStatusEnum_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  InfaasRequestStatusEnum_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool InfaasRequestStatusEnum_IsValid(int value);
constexpr InfaasRequestStatusEnum InfaasRequestStatusEnum_MIN = INVALID;
constexpr InfaasRequestStatusEnum InfaasRequestStatusEnum_MAX = UNAVAILABLE;
constexpr int InfaasRequestStatusEnum_ARRAYSIZE = InfaasRequestStatusEnum_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* InfaasRequestStatusEnum_descriptor();
template<typename T>
inline const std::string& InfaasRequestStatusEnum_Name(T enum_t_value) {
  static_assert(::std::is_same<T, InfaasRequestStatusEnum>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function InfaasRequestStatusEnum_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    InfaasRequestStatusEnum_descriptor(), enum_t_value);
}
inline bool InfaasRequestStatusEnum_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, InfaasRequestStatusEnum* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<InfaasRequestStatusEnum>(
    InfaasRequestStatusEnum_descriptor(), name, value);
}
// ===================================================================

class InfaasRequestStatus final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:infaas.internal.InfaasRequestStatus) */ {
 public:
  inline InfaasRequestStatus() : InfaasRequestStatus(nullptr) {}
  ~InfaasRequestStatus() override;
  explicit constexpr InfaasRequestStatus(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InfaasRequestStatus(const InfaasRequestStatus& from);
  InfaasRequestStatus(InfaasRequestStatus&& from) noexcept
    : InfaasRequestStatus() {
    *this = ::std::move(from);
  }

  inline InfaasRequestStatus& operator=(const InfaasRequestStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline InfaasRequestStatus& operator=(InfaasRequestStatus&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InfaasRequestStatus& default_instance() {
    return *internal_default_instance();
  }
  static inline const InfaasRequestStatus* internal_default_instance() {
    return reinterpret_cast<const InfaasRequestStatus*>(
               &_InfaasRequestStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(InfaasRequestStatus& a, InfaasRequestStatus& b) {
    a.Swap(&b);
  }
  inline void Swap(InfaasRequestStatus* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InfaasRequestStatus* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InfaasRequestStatus* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InfaasRequestStatus>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InfaasRequestStatus& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const InfaasRequestStatus& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InfaasRequestStatus* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "infaas.internal.InfaasRequestStatus";
  }
  protected:
  explicit InfaasRequestStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgFieldNumber = 2,
    kStatusFieldNumber = 1,
  };
  // string msg = 2;
  void clear_msg();
  const std::string& msg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_msg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_msg();
  PROTOBUF_NODISCARD std::string* release_msg();
  void set_allocated_msg(std::string* msg);
  private:
  const std::string& _internal_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_msg(const std::string& value);
  std::string* _internal_mutable_msg();
  public:

  // .infaas.internal.InfaasRequestStatusEnum status = 1;
  void clear_status();
  ::infaas::internal::InfaasRequestStatusEnum status() const;
  void set_status(::infaas::internal::InfaasRequestStatusEnum value);
  private:
  ::infaas::internal::InfaasRequestStatusEnum _internal_status() const;
  void _internal_set_status(::infaas::internal::InfaasRequestStatusEnum value);
  public:

  // @@protoc_insertion_point(class_scope:infaas.internal.InfaasRequestStatus)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_;
  int status_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_infaas_5frequest_5fstatus_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// InfaasRequestStatus

// .infaas.internal.InfaasRequestStatusEnum status = 1;
inline void InfaasRequestStatus::clear_status() {
  status_ = 0;
}
inline ::infaas::internal::InfaasRequestStatusEnum InfaasRequestStatus::_internal_status() const {
  return static_cast< ::infaas::internal::InfaasRequestStatusEnum >(status_);
}
inline ::infaas::internal::InfaasRequestStatusEnum InfaasRequestStatus::status() const {
  // @@protoc_insertion_point(field_get:infaas.internal.InfaasRequestStatus.status)
  return _internal_status();
}
inline void InfaasRequestStatus::_internal_set_status(::infaas::internal::InfaasRequestStatusEnum value) {
  
  status_ = value;
}
inline void InfaasRequestStatus::set_status(::infaas::internal::InfaasRequestStatusEnum value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:infaas.internal.InfaasRequestStatus.status)
}

// string msg = 2;
inline void InfaasRequestStatus::clear_msg() {
  msg_.ClearToEmpty();
}
inline const std::string& InfaasRequestStatus::msg() const {
  // @@protoc_insertion_point(field_get:infaas.internal.InfaasRequestStatus.msg)
  return _internal_msg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void InfaasRequestStatus::set_msg(ArgT0&& arg0, ArgT... args) {
 
 msg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:infaas.internal.InfaasRequestStatus.msg)
}
inline std::string* InfaasRequestStatus::mutable_msg() {
  std::string* _s = _internal_mutable_msg();
  // @@protoc_insertion_point(field_mutable:infaas.internal.InfaasRequestStatus.msg)
  return _s;
}
inline const std::string& InfaasRequestStatus::_internal_msg() const {
  return msg_.Get();
}
inline void InfaasRequestStatus::_internal_set_msg(const std::string& value) {
  
  msg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* InfaasRequestStatus::_internal_mutable_msg() {
  
  return msg_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* InfaasRequestStatus::release_msg() {
  // @@protoc_insertion_point(field_release:infaas.internal.InfaasRequestStatus.msg)
  return msg_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void InfaasRequestStatus::set_allocated_msg(std::string* msg) {
  if (msg != nullptr) {
    
  } else {
    
  }
  msg_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), msg,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (msg_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    msg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:infaas.internal.InfaasRequestStatus.msg)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace internal
}  // namespace infaas

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::infaas::internal::InfaasRequestStatusEnum> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::infaas::internal::InfaasRequestStatusEnum>() {
  return ::infaas::internal::InfaasRequestStatusEnum_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_infaas_5frequest_5fstatus_2eproto
