# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: infaas_request_status.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'infaas_request_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1binfaas_request_status.proto\x12\x0finfaas.internal\"\\\n\x13InfaasRequestStatus\x12\x38\n\x06status\x18\x01 \x01(\x0e\x32(.infaas.internal.InfaasRequestStatusEnum\x12\x0b\n\x03msg\x18\x02 \x01(\t*D\n\x17InfaasRequestStatusEnum\x12\x0b\n\x07INVALID\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x0f\n\x0bUNAVAILABLE\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'infaas_request_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFAASREQUESTSTATUSENUM']._serialized_start=142
  _globals['_INFAASREQUESTSTATUSENUM']._serialized_end=210
  _globals['_INFAASREQUESTSTATUS']._serialized_start=48
  _globals['_INFAASREQUESTSTATUS']._serialized_end=140
# @@protoc_insertion_point(module_scope)
