# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import infaas_request_status_pb2 as infaas__request__status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bquery.proto\x12\x0finfaas.internal\x1a\x1binfaas_request_status.proto\"g\n\x12QueryOnlineRequest\x12\x0e\n\x06Prompt\x18\x01 \x03(\t\x12\r\n\x05Steps\x18\x02 \x01(\x05\x12\x11\n\tCFG_Scale\x18\x03 \x01(\x02\x12\x11\n\tBatchSize\x18\x04 \x01(\x05\x12\x0c\n\x04Seed\x18\x05 \x01(\x03\"G\n\x08QuerySLO\x12\x15\n\rLatencyInUSec\x18\x01 \x01(\x03\x12\x13\n\x0bMinAccuracy\x18\x02 \x01(\x02\x12\x0f\n\x07MaxCost\x18\x03 \x01(\x02\"`\n\x13QueryOnlineResponse\x12\x13\n\x0bimage_paths\x18\x01 \x03(\t\x12\x34\n\x06status\x18\x02 \x01(\x0b\x32$.infaas.internal.InfaasRequestStatus\"h\n\x13QueryOfflineRequest\x12\x0e\n\x06Prompt\x18\x01 \x01(\t\x12\r\n\x05Steps\x18\x02 \x01(\x05\x12\x11\n\tCFG_Scale\x18\x03 \x01(\x02\x12\x11\n\tBatchSize\x18\x04 \x01(\x05\x12\x0c\n\x04Seed\x18\x05 \x01(\x03\"L\n\x14QueryOfflineResponse\x12\x34\n\x06status\x18\x01 \x01(\x0b\x32$.infaas.internal.InfaasRequestStatus\"H\n\x10HeartbeatRequest\x12\x34\n\x06status\x18\x01 \x01(\x0b\x32$.infaas.internal.InfaasRequestStatus\"I\n\x11HeartbeatResponse\x12\x34\n\x06status\x18\x01 \x01(\x0b\x32$.infaas.internal.InfaasRequestStatus2\x98\x02\n\x05Query\x12Z\n\x0bQueryOnline\x12#.infaas.internal.QueryOnlineRequest\x1a$.infaas.internal.QueryOnlineResponse\"\x00\x12]\n\x0cQueryOffline\x12$.infaas.internal.QueryOfflineRequest\x1a%.infaas.internal.QueryOfflineResponse\"\x00\x12T\n\tHeartbeat\x12!.infaas.internal.HeartbeatRequest\x1a\".infaas.internal.HeartbeatResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYONLINEREQUEST']._serialized_start=61
  _globals['_QUERYONLINEREQUEST']._serialized_end=164
  _globals['_QUERYSLO']._serialized_start=166
  _globals['_QUERYSLO']._serialized_end=237
  _globals['_QUERYONLINERESPONSE']._serialized_start=239
  _globals['_QUERYONLINERESPONSE']._serialized_end=335
  _globals['_QUERYOFFLINEREQUEST']._serialized_start=337
  _globals['_QUERYOFFLINEREQUEST']._serialized_end=441
  _globals['_QUERYOFFLINERESPONSE']._serialized_start=443
  _globals['_QUERYOFFLINERESPONSE']._serialized_end=519
  _globals['_HEARTBEATREQUEST']._serialized_start=521
  _globals['_HEARTBEATREQUEST']._serialized_end=593
  _globals['_HEARTBEATRESPONSE']._serialized_start=595
  _globals['_HEARTBEATRESPONSE']._serialized_end=668
  _globals['_QUERY']._serialized_start=671
  _globals['_QUERY']._serialized_end=951
# @@protoc_insertion_point(module_scope)
