# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import query_pb2 as query__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in query_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QueryStub(object):
    """Service provided by the workers that the master can talk to.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryOnline = channel.unary_unary(
                '/infaas.internal.Query/QueryOnline',
                request_serializer=query__pb2.QueryOnlineRequest.SerializeToString,
                response_deserializer=query__pb2.QueryOnlineResponse.FromString,
                _registered_method=True)
        self.QueryOffline = channel.unary_unary(
                '/infaas.internal.Query/QueryOffline',
                request_serializer=query__pb2.QueryOfflineRequest.SerializeToString,
                response_deserializer=query__pb2.QueryOfflineResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/infaas.internal.Query/Heartbeat',
                request_serializer=query__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=query__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class QueryServicer(object):
    """Service provided by the workers that the master can talk to.
    """

    def QueryOnline(self, request, context):
        """Online query, send input data in the payload
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryOffline(self, request, context):
        """Offline query, input data are stored on the cloud
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryOnline': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryOnline,
                    request_deserializer=query__pb2.QueryOnlineRequest.FromString,
                    response_serializer=query__pb2.QueryOnlineResponse.SerializeToString,
            ),
            'QueryOffline': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryOffline,
                    request_deserializer=query__pb2.QueryOfflineRequest.FromString,
                    response_serializer=query__pb2.QueryOfflineResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=query__pb2.HeartbeatRequest.FromString,
                    response_serializer=query__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'infaas.internal.Query', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('infaas.internal.Query', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Query(object):
    """Service provided by the workers that the master can talk to.
    """

    @staticmethod
    def QueryOnline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/infaas.internal.Query/QueryOnline',
            query__pb2.QueryOnlineRequest.SerializeToString,
            query__pb2.QueryOnlineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryOffline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/infaas.internal.Query/QueryOffline',
            query__pb2.QueryOfflineRequest.SerializeToString,
            query__pb2.QueryOfflineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/infaas.internal.Query/Heartbeat',
            query__pb2.HeartbeatRequest.SerializeToString,
            query__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
