# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: diffusion_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'diffusion_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64iffusion_service.proto\x12\x0finfaas.internal\"u\n\x10\x44iffusionRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\r\n\x05steps\x18\x02 \x01(\x05\x12\x15\n\rguidanceScale\x18\x03 \x01(\x02\x12\x0c\n\x04seed\x18\x04 \x01(\x05\x12\r\n\x05width\x18\x05 \x01(\x05\x12\x0e\n\x06height\x18\x06 \x01(\x05\"B\n\x0e\x44iffusionReply\x12\x11\n\timage_png\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x32\x62\n\x10\x44iffusionService\x12N\n\x08Generate\x12!.infaas.internal.DiffusionRequest\x1a\x1f.infaas.internal.DiffusionReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'diffusion_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DIFFUSIONREQUEST']._serialized_start=44
  _globals['_DIFFUSIONREQUEST']._serialized_end=161
  _globals['_DIFFUSIONREPLY']._serialized_start=163
  _globals['_DIFFUSIONREPLY']._serialized_end=229
  _globals['_DIFFUSIONSERVICE']._serialized_start=231
  _globals['_DIFFUSIONSERVICE']._serialized_end=329
# @@protoc_insertion_point(module_scope)
