// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: modelreg.proto
// Original file comments:
// Public API for users to register models with INFaaS
//
#ifndef GRPC_modelreg_2eproto__INCLUDED
#define GRPC_modelreg_2eproto__INCLUDED

#include "modelreg.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace infaaspublic {
namespace infaasmodelreg {

// Defining the model registration service
class ModelReg final {
 public:
  static constexpr char const* service_full_name() {
    return "infaaspublic.infaasmodelreg.ModelReg";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Heartbeat
    virtual ::grpc::Status Heartbeat(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::HeartbeatRequest& request, ::infaaspublic::infaasmodelreg::HeartbeatResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::infaaspublic::infaasmodelreg::HeartbeatResponse>> AsyncHeartbeat(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::infaaspublic::infaasmodelreg::HeartbeatResponse>>(AsyncHeartbeatRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::infaaspublic::infaasmodelreg::HeartbeatResponse>> PrepareAsyncHeartbeat(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::infaaspublic::infaasmodelreg::HeartbeatResponse>>(PrepareAsyncHeartbeatRaw(context, request, cq));
    }
    // Register a model
    virtual ::grpc::Status RegisterModel(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::ModelRegRequest& request, ::infaaspublic::infaasmodelreg::ModelRegResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::infaaspublic::infaasmodelreg::ModelRegResponse>> AsyncRegisterModel(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::ModelRegRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::infaaspublic::infaasmodelreg::ModelRegResponse>>(AsyncRegisterModelRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::infaaspublic::infaasmodelreg::ModelRegResponse>> PrepareAsyncRegisterModel(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::ModelRegRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::infaaspublic::infaasmodelreg::ModelRegResponse>>(PrepareAsyncRegisterModelRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Heartbeat
      virtual void Heartbeat(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::HeartbeatRequest* request, ::infaaspublic::infaasmodelreg::HeartbeatResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Heartbeat(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::HeartbeatRequest* request, ::infaaspublic::infaasmodelreg::HeartbeatResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Register a model
      virtual void RegisterModel(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::ModelRegRequest* request, ::infaaspublic::infaasmodelreg::ModelRegResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RegisterModel(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::ModelRegRequest* request, ::infaaspublic::infaasmodelreg::ModelRegResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::infaaspublic::infaasmodelreg::HeartbeatResponse>* AsyncHeartbeatRaw(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::infaaspublic::infaasmodelreg::HeartbeatResponse>* PrepareAsyncHeartbeatRaw(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::infaaspublic::infaasmodelreg::ModelRegResponse>* AsyncRegisterModelRaw(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::ModelRegRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::infaaspublic::infaasmodelreg::ModelRegResponse>* PrepareAsyncRegisterModelRaw(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::ModelRegRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Heartbeat(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::HeartbeatRequest& request, ::infaaspublic::infaasmodelreg::HeartbeatResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::infaaspublic::infaasmodelreg::HeartbeatResponse>> AsyncHeartbeat(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::infaaspublic::infaasmodelreg::HeartbeatResponse>>(AsyncHeartbeatRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::infaaspublic::infaasmodelreg::HeartbeatResponse>> PrepareAsyncHeartbeat(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::infaaspublic::infaasmodelreg::HeartbeatResponse>>(PrepareAsyncHeartbeatRaw(context, request, cq));
    }
    ::grpc::Status RegisterModel(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::ModelRegRequest& request, ::infaaspublic::infaasmodelreg::ModelRegResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::infaaspublic::infaasmodelreg::ModelRegResponse>> AsyncRegisterModel(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::ModelRegRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::infaaspublic::infaasmodelreg::ModelRegResponse>>(AsyncRegisterModelRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::infaaspublic::infaasmodelreg::ModelRegResponse>> PrepareAsyncRegisterModel(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::ModelRegRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::infaaspublic::infaasmodelreg::ModelRegResponse>>(PrepareAsyncRegisterModelRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Heartbeat(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::HeartbeatRequest* request, ::infaaspublic::infaasmodelreg::HeartbeatResponse* response, std::function<void(::grpc::Status)>) override;
      void Heartbeat(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::HeartbeatRequest* request, ::infaaspublic::infaasmodelreg::HeartbeatResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void RegisterModel(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::ModelRegRequest* request, ::infaaspublic::infaasmodelreg::ModelRegResponse* response, std::function<void(::grpc::Status)>) override;
      void RegisterModel(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::ModelRegRequest* request, ::infaaspublic::infaasmodelreg::ModelRegResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::infaaspublic::infaasmodelreg::HeartbeatResponse>* AsyncHeartbeatRaw(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::infaaspublic::infaasmodelreg::HeartbeatResponse>* PrepareAsyncHeartbeatRaw(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::infaaspublic::infaasmodelreg::ModelRegResponse>* AsyncRegisterModelRaw(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::ModelRegRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::infaaspublic::infaasmodelreg::ModelRegResponse>* PrepareAsyncRegisterModelRaw(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::ModelRegRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Heartbeat_;
    const ::grpc::internal::RpcMethod rpcmethod_RegisterModel_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Heartbeat
    virtual ::grpc::Status Heartbeat(::grpc::ServerContext* context, const ::infaaspublic::infaasmodelreg::HeartbeatRequest* request, ::infaaspublic::infaasmodelreg::HeartbeatResponse* response);
    // Register a model
    virtual ::grpc::Status RegisterModel(::grpc::ServerContext* context, const ::infaaspublic::infaasmodelreg::ModelRegRequest* request, ::infaaspublic::infaasmodelreg::ModelRegResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Heartbeat() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::infaaspublic::infaasmodelreg::HeartbeatRequest* /*request*/, ::infaaspublic::infaasmodelreg::HeartbeatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHeartbeat(::grpc::ServerContext* context, ::infaaspublic::infaasmodelreg::HeartbeatRequest* request, ::grpc::ServerAsyncResponseWriter< ::infaaspublic::infaasmodelreg::HeartbeatResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RegisterModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RegisterModel() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_RegisterModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterModel(::grpc::ServerContext* /*context*/, const ::infaaspublic::infaasmodelreg::ModelRegRequest* /*request*/, ::infaaspublic::infaasmodelreg::ModelRegResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterModel(::grpc::ServerContext* context, ::infaaspublic::infaasmodelreg::ModelRegRequest* request, ::grpc::ServerAsyncResponseWriter< ::infaaspublic::infaasmodelreg::ModelRegResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Heartbeat<WithAsyncMethod_RegisterModel<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Heartbeat() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::infaaspublic::infaasmodelreg::HeartbeatRequest, ::infaaspublic::infaasmodelreg::HeartbeatResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::infaaspublic::infaasmodelreg::HeartbeatRequest* request, ::infaaspublic::infaasmodelreg::HeartbeatResponse* response) { return this->Heartbeat(context, request, response); }));}
    void SetMessageAllocatorFor_Heartbeat(
        ::grpc::MessageAllocator< ::infaaspublic::infaasmodelreg::HeartbeatRequest, ::infaaspublic::infaasmodelreg::HeartbeatResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::infaaspublic::infaasmodelreg::HeartbeatRequest, ::infaaspublic::infaasmodelreg::HeartbeatResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::infaaspublic::infaasmodelreg::HeartbeatRequest* /*request*/, ::infaaspublic::infaasmodelreg::HeartbeatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Heartbeat(
      ::grpc::CallbackServerContext* /*context*/, const ::infaaspublic::infaasmodelreg::HeartbeatRequest* /*request*/, ::infaaspublic::infaasmodelreg::HeartbeatResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_RegisterModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RegisterModel() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::infaaspublic::infaasmodelreg::ModelRegRequest, ::infaaspublic::infaasmodelreg::ModelRegResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::infaaspublic::infaasmodelreg::ModelRegRequest* request, ::infaaspublic::infaasmodelreg::ModelRegResponse* response) { return this->RegisterModel(context, request, response); }));}
    void SetMessageAllocatorFor_RegisterModel(
        ::grpc::MessageAllocator< ::infaaspublic::infaasmodelreg::ModelRegRequest, ::infaaspublic::infaasmodelreg::ModelRegResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::infaaspublic::infaasmodelreg::ModelRegRequest, ::infaaspublic::infaasmodelreg::ModelRegResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RegisterModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterModel(::grpc::ServerContext* /*context*/, const ::infaaspublic::infaasmodelreg::ModelRegRequest* /*request*/, ::infaaspublic::infaasmodelreg::ModelRegResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterModel(
      ::grpc::CallbackServerContext* /*context*/, const ::infaaspublic::infaasmodelreg::ModelRegRequest* /*request*/, ::infaaspublic::infaasmodelreg::ModelRegResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Heartbeat<WithCallbackMethod_RegisterModel<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Heartbeat() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::infaaspublic::infaasmodelreg::HeartbeatRequest* /*request*/, ::infaaspublic::infaasmodelreg::HeartbeatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RegisterModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RegisterModel() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_RegisterModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterModel(::grpc::ServerContext* /*context*/, const ::infaaspublic::infaasmodelreg::ModelRegRequest* /*request*/, ::infaaspublic::infaasmodelreg::ModelRegResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Heartbeat() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::infaaspublic::infaasmodelreg::HeartbeatRequest* /*request*/, ::infaaspublic::infaasmodelreg::HeartbeatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHeartbeat(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RegisterModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RegisterModel() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_RegisterModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterModel(::grpc::ServerContext* /*context*/, const ::infaaspublic::infaasmodelreg::ModelRegRequest* /*request*/, ::infaaspublic::infaasmodelreg::ModelRegResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterModel(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Heartbeat() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Heartbeat(context, request, response); }));
    }
    ~WithRawCallbackMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::infaaspublic::infaasmodelreg::HeartbeatRequest* /*request*/, ::infaaspublic::infaasmodelreg::HeartbeatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Heartbeat(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RegisterModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RegisterModel() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RegisterModel(context, request, response); }));
    }
    ~WithRawCallbackMethod_RegisterModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterModel(::grpc::ServerContext* /*context*/, const ::infaaspublic::infaasmodelreg::ModelRegRequest* /*request*/, ::infaaspublic::infaasmodelreg::ModelRegResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterModel(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Heartbeat() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::infaaspublic::infaasmodelreg::HeartbeatRequest, ::infaaspublic::infaasmodelreg::HeartbeatResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::infaaspublic::infaasmodelreg::HeartbeatRequest, ::infaaspublic::infaasmodelreg::HeartbeatResponse>* streamer) {
                       return this->StreamedHeartbeat(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::infaaspublic::infaasmodelreg::HeartbeatRequest* /*request*/, ::infaaspublic::infaasmodelreg::HeartbeatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHeartbeat(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::infaaspublic::infaasmodelreg::HeartbeatRequest,::infaaspublic::infaasmodelreg::HeartbeatResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RegisterModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RegisterModel() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::infaaspublic::infaasmodelreg::ModelRegRequest, ::infaaspublic::infaasmodelreg::ModelRegResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::infaaspublic::infaasmodelreg::ModelRegRequest, ::infaaspublic::infaasmodelreg::ModelRegResponse>* streamer) {
                       return this->StreamedRegisterModel(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RegisterModel() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RegisterModel(::grpc::ServerContext* /*context*/, const ::infaaspublic::infaasmodelreg::ModelRegRequest* /*request*/, ::infaaspublic::infaasmodelreg::ModelRegResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRegisterModel(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::infaaspublic::infaasmodelreg::ModelRegRequest,::infaaspublic::infaasmodelreg::ModelRegResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Heartbeat<WithStreamedUnaryMethod_RegisterModel<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Heartbeat<WithStreamedUnaryMethod_RegisterModel<Service > > StreamedService;
};

}  // namespace infaasmodelreg
}  // namespace infaaspublic


#endif  // GRPC_modelreg_2eproto__INCLUDED
