// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: modelreg.proto

#include "modelreg.pb.h"
#include "modelreg.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace infaaspublic {
namespace infaasmodelreg {

static const char* ModelReg_method_names[] = {
  "/infaaspublic.infaasmodelreg.ModelReg/Heartbeat",
  "/infaaspublic.infaasmodelreg.ModelReg/RegisterModel",
};

std::unique_ptr< ModelReg::Stub> ModelReg::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ModelReg::Stub> stub(new ModelReg::Stub(channel, options));
  return stub;
}

ModelReg::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Heartbeat_(ModelReg_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RegisterModel_(ModelReg_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ModelReg::Stub::Heartbeat(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::HeartbeatRequest& request, ::infaaspublic::infaasmodelreg::HeartbeatResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::infaaspublic::infaasmodelreg::HeartbeatRequest, ::infaaspublic::infaasmodelreg::HeartbeatResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Heartbeat_, context, request, response);
}

void ModelReg::Stub::async::Heartbeat(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::HeartbeatRequest* request, ::infaaspublic::infaasmodelreg::HeartbeatResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::infaaspublic::infaasmodelreg::HeartbeatRequest, ::infaaspublic::infaasmodelreg::HeartbeatResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Heartbeat_, context, request, response, std::move(f));
}

void ModelReg::Stub::async::Heartbeat(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::HeartbeatRequest* request, ::infaaspublic::infaasmodelreg::HeartbeatResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Heartbeat_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::infaaspublic::infaasmodelreg::HeartbeatResponse>* ModelReg::Stub::PrepareAsyncHeartbeatRaw(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::infaaspublic::infaasmodelreg::HeartbeatResponse, ::infaaspublic::infaasmodelreg::HeartbeatRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Heartbeat_, context, request);
}

::grpc::ClientAsyncResponseReader< ::infaaspublic::infaasmodelreg::HeartbeatResponse>* ModelReg::Stub::AsyncHeartbeatRaw(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHeartbeatRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ModelReg::Stub::RegisterModel(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::ModelRegRequest& request, ::infaaspublic::infaasmodelreg::ModelRegResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::infaaspublic::infaasmodelreg::ModelRegRequest, ::infaaspublic::infaasmodelreg::ModelRegResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RegisterModel_, context, request, response);
}

void ModelReg::Stub::async::RegisterModel(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::ModelRegRequest* request, ::infaaspublic::infaasmodelreg::ModelRegResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::infaaspublic::infaasmodelreg::ModelRegRequest, ::infaaspublic::infaasmodelreg::ModelRegResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterModel_, context, request, response, std::move(f));
}

void ModelReg::Stub::async::RegisterModel(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::ModelRegRequest* request, ::infaaspublic::infaasmodelreg::ModelRegResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterModel_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::infaaspublic::infaasmodelreg::ModelRegResponse>* ModelReg::Stub::PrepareAsyncRegisterModelRaw(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::ModelRegRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::infaaspublic::infaasmodelreg::ModelRegResponse, ::infaaspublic::infaasmodelreg::ModelRegRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RegisterModel_, context, request);
}

::grpc::ClientAsyncResponseReader< ::infaaspublic::infaasmodelreg::ModelRegResponse>* ModelReg::Stub::AsyncRegisterModelRaw(::grpc::ClientContext* context, const ::infaaspublic::infaasmodelreg::ModelRegRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterModelRaw(context, request, cq);
  result->StartCall();
  return result;
}

ModelReg::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ModelReg_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ModelReg::Service, ::infaaspublic::infaasmodelreg::HeartbeatRequest, ::infaaspublic::infaasmodelreg::HeartbeatResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ModelReg::Service* service,
             ::grpc::ServerContext* ctx,
             const ::infaaspublic::infaasmodelreg::HeartbeatRequest* req,
             ::infaaspublic::infaasmodelreg::HeartbeatResponse* resp) {
               return service->Heartbeat(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ModelReg_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ModelReg::Service, ::infaaspublic::infaasmodelreg::ModelRegRequest, ::infaaspublic::infaasmodelreg::ModelRegResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ModelReg::Service* service,
             ::grpc::ServerContext* ctx,
             const ::infaaspublic::infaasmodelreg::ModelRegRequest* req,
             ::infaaspublic::infaasmodelreg::ModelRegResponse* resp) {
               return service->RegisterModel(ctx, req, resp);
             }, this)));
}

ModelReg::Service::~Service() {
}

::grpc::Status ModelReg::Service::Heartbeat(::grpc::ServerContext* context, const ::infaaspublic::infaasmodelreg::HeartbeatRequest* request, ::infaaspublic::infaasmodelreg::HeartbeatResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ModelReg::Service::RegisterModel(::grpc::ServerContext* context, const ::infaaspublic::infaasmodelreg::ModelRegRequest* request, ::infaaspublic::infaasmodelreg::ModelRegResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace infaaspublic
}  // namespace infaasmodelreg

